### ISSUE TITLE
BoundsError using curve_fit with Julia 0.5

### ISSUE THREAD

**Issue by julian-wolf** [JuliaOpt/LsqFit.jl#28] opened 2016-12-13 18:53 UTC
When running the example code given in the README:

    using LsqFit
    model(x, p) = p[1]*exp(-x.*p[2])
    xdata = linspace(0,10,20)
    ydata = model(xdata, [1.0 2.0]) + 0.01*randn(length(xdata))
    fit = curve_fit(model, xdata, ydata, [0.5, 0.5])

I get the following error:

    ERROR: BoundsError
     in getindex at ./number.jl:21 [inlined]
     in model(::LinSpace{Float64}, ::Float64) at ./REPL[98]:1
     in f at /Users/julian/.julia/v0.5/LsqFit/src/curve_fit.jl:38 [inlined]
     in #lmfit#1(::Array{Any,1}, ::Function, ::LsqFit.#f#3{#model,LinSpace{Float64},Array{Float64,1}}, ::Array{Float64,1}) at /Users/julian/.julia/v0.5/LsqFit/src/curve_fit.jl:31
     in #curve_fit#2(::Array{Any,1}, ::Function, ::#model, ::LinSpace{Float64}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/julian/.julia/v0.5/LsqFit/src/curve_fit.jl:39
     in curve_fit(::Function, ::LinSpace{Float64}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/julian/.julia/v0.5/LsqFit/src/curve_fit.jl:38

Here's my `versioninfo()`:

    Julia Version 0.5.0
    Commit 3c9d753 (2016-09-19 18:14 UTC)
    Platform Info:
      System: Darwin (x86_64-apple-darwin13.4.0)
      CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by mzaffalon** [comment] 2016-12-14 04:28
It's related to #19.

**Comment by blakejohnson** [comment] 2016-12-15 22:08
Basically a duplicate of #23. Should be fixed by the newly tagged version.

**Closed by blakejohnson** 2016-12-15 22:08 UTC
