### ISSUE TITLE
warning | MultivariateOptimizationResults

### ISSUE THREAD

**Issue by missperovaz** [JuliaOpt/LsqFit.jl#31] opened 2017-01-09 16:18 UTC
I'm getting the following warning each time fit_curve is executed.

I appreciate any thoughts on it. Should I be using Optim.jl or GLM.jl for regression instead on Julia 5.0?

Thanks,

```
WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,0) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{LsqFit.LevenbergMarquardt},1}, ::Int64, ::Int64) at ./deprecated.jl:50
 in #levenberg_marquardt#1(::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::LsqFit.#f#4{#model_expon,Array{Float64,1},Array{Float64,1}}, ::Calculus.#g#5{LsqFit.#f#4{#model_expon,Array{Float64,1},Array{Float64,1}},Symbol}, ::Array{Float64,1}) at /Users/brumc/.julia/v0.5/LsqFit/src/levenberg_marquardt.jl:169
 in (::LsqFit.#kw##levenberg_marquardt)(::Array{Any,1}, ::LsqFit.#levenberg_marquardt, ::Function, ::Function, ::Array{Float64,1}) at ./<missing>:0
 in #lmfit#2(::Array{Any,1}, ::Function, ::LsqFit.#f#4{#model_expon,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}) at /Users/brumc/.julia/v0.5/LsqFit/src/curve_fit.jl:29
 in (::LsqFit.#kw##lmfit)(::Array{Any,1}, ::LsqFit.#lmfit, ::Function, ::Array{Float64,1}) at ./<missing>:0
 in #curve_fit#3(::Array{Any,1}, ::Function, ::#model_expon, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/brumc/.julia/v0.5/LsqFit/src/curve_fit.jl:43
 in (::LsqFit.#kw##curve_fit)(::Array{Any,1}, ::LsqFit.#curve_fit, ::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at ./<missing>:0
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String, ::Int64) at /Users/brumc/.julia/v0.5/CodeTools/src/eval.jl:28
 in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at /Users/brumc/.julia/v0.5/CodeTools/src/eval.jl:32
 in (::Atom.##55#58{String,Int64,String})() at /Users/brumc/.julia/v0.5/Atom/src/eval.jl:40
 in withpath(::Atom.##55#58{String,Int64,String}, ::String) at /Users/brumc/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::String) at /Users/brumc/.julia/v0.5/Atom/src/eval.jl:46
 in macro expansion at /Users/brumc/.julia/v0.5/Atom/src/eval.jl:57 [inlined]
 in (::Atom.##54#57{String,Int64,String})() at ./task.jl:60
while loading /Users/brumc/Documents/code/soli/unit_test/dt_tunning_cfar.jl, in expression starting on line 153
```

**Comment by blakejohnson** [comment] 2017-01-09 16:31
If you are doing non-linear regression, Optim.jl and GLM.jl won't help you. I'll look into this warning.

**Comment by missperovaz** [comment] 2017-01-09 17:49
thanks @blakejohnson , let me know if I can test anything on my end.

**Comment by blakejohnson** [comment] 2017-01-09 18:55
@missperovaz looks like this is already fixed on LsqFit.jl master. Can you try `Pkg.checkout("LsqFit")` and confirm? If so, I will tag a new release.

**Comment by missperovaz** [comment] 2017-01-09 19:54
awesome, thanks,
I got this for 2 out of 100 runs, but I guess my data is to be blamed, right?

```
WARNING: Problem solving for delta_x: predicted residual increase.
1.4705261997799471e7 (predicted_residual) >
1.4705261997799465e7 (residual) + 1.862645149230957e-9 (eps)
```

**Comment by blakejohnson** [comment] 2017-01-09 20:21
That's just some (mostly harmless) numerical noise in the solver. Looks like we need to be a little smarter in testing whether the calculated `delta_x` is valid, since the test is assuming that the residual is O(1), whereas in your case it is 10^7.

**Comment by blakejohnson** [comment] 2017-01-09 20:57
New version is tagged and should be automatically available in a day or two.

**Closed by blakejohnson** 2017-01-09 20:57 UTC

**Comment by missperovaz** [comment] 2017-01-09 21:11
thanks a lot

carolina
     __o
  _`\<,_
(+) / (+)

www.carolinabrum.com
(avast users: turn it off pls)
